package com.goods.entities;
// Generated by Hibernate Tools 4.3.1


import com.goods.entities.Goods;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.SEQUENCE;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import com.goods.entities.Orders;

/**
 * Goodslist generated by hbm2java
 */
@Entity
@Table(name = "goodslist")
public class Goodslist implements java.io.Serializable {


    private Integer goodslistid;
    private Goods goods;
    private Orders orders;
    private int count;
    private String length;
    private String width;
    private String height;
    private String depth;


    @SequenceGenerator(name = "generator", sequenceName = "goodslist_sequence")
    @Id
    @GeneratedValue(strategy = SEQUENCE, generator = "generator")
    @Column(name = "goodslistid", unique = true, nullable = false)
    public Integer getGoodslistid() {
        return this.goodslistid;
    }

    public void setGoodslistid(Integer goodslistid) {
        this.goodslistid = goodslistid;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "goodid")
    public Goods getGoods() {
        return this.goods;
    }

    public void setGoods(Goods goods) {
        this.goods = goods;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "orderid")
    public Orders getOrders() {
        return this.orders;
    }

    public void setOrders(Orders orders) {
        this.orders = orders;
    }

    @Column(name = "count", nullable = false)
    public int getCount() {
        return this.count;
    }

    public void setCount(int count) {
        this.count = count;
    }

    @Column(name = "length", length = 50)
    public String getLength() {
        return this.length;
    }

    public void setLength(String length) {
        this.length = length;
    }

    @Column(name = "width", length = 50)
    public String getWidth() {
        return this.width;
    }

    public void setWidth(String width) {
        this.width = width;
    }

    @Column(name = "height", length = 50)
    public String getHeight() {
        return this.height;
    }

    public void setHeight(String height) {
        this.height = height;
    }

    @Column(name = "depth", length = 50)
    public String getDepth() {
        return this.depth;
    }

    public void setDepth(String depth) {
        this.depth = depth;
    }


}
