package com.goods.entities;
// Generated by Hibernate Tools 4.3.1


import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.SEQUENCE;

import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Goods generated by hbm2java
 */
@Entity
@Table(name = "goods")
@AllArgsConstructor
@NoArgsConstructor
public class Goods implements java.io.Serializable {


    private Integer goodid;
    private String goodname;

    public Goods(String goodname) {
        this.goodname = goodname;
    }

    @SequenceGenerator(name = "seq_goods", sequenceName = "seq_goods", initialValue = 1)
    @Id
    @GeneratedValue(strategy = SEQUENCE, generator = "seq_goods")
    @Column(name = "goodid", unique = true, nullable = false)
    public Integer getGoodid() {
        return this.goodid;
    }

    public void setGoodid(Integer goodid) {
        this.goodid = goodid;
    }

    @Column(name = "goodname", nullable = false, length = 100)
    public String getGoodname() {
        return this.goodname;
    }

    public void setGoodname(String goodname) {
        this.goodname = goodname;
    }
}
