package com.goods.entities;
// Generated by Hibernate Tools 4.3.1


import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.SEQUENCE;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Orders generated by hbm2java
 */
@Entity
@Table(name = "orders")
@AllArgsConstructor
@NoArgsConstructor
public class Orders implements java.io.Serializable {


    private Integer orderid;
    private Users users;
    private String ordernunber;
    private Date createdate;

    @SequenceGenerator(name = "seq_orders", sequenceName = "seq_orders")
    @Id
    @GeneratedValue(strategy = SEQUENCE, generator = "seq_orders")
    @Column(name = "orderid", unique = true, nullable = false)
    public Integer getOrderid() {
        return this.orderid;
    }

    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "createby")
    public Users getUsers() {
        return this.users;
    }

    public void setUsers(Users users) {
        this.users = users;
    }

    @Column(name = "ordernunber", length = 20)
    public String getOrdernunber() {
        return this.ordernunber;
    }

    public void setOrdernunber(String ordernunber) {
        this.ordernunber = ordernunber;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "createdate", length = 29)
    public Date getCreatedate() {
        return this.createdate;
    }

    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }


}
