package com.goods.entities;
// Generated by Hibernate Tools 4.3.1


import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.SEQUENCE;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Works generated by hbm2java
 */
@Entity
@Table(name = "works")
@AllArgsConstructor
@NoArgsConstructor
public class Works implements java.io.Serializable {


    private Integer workid;
    private Goods goods;
    private String workname;
    private double norma;
    private int count;

    @SequenceGenerator(name = "seq_works", sequenceName = "seq_works")
    @Id
    @GeneratedValue(strategy = SEQUENCE, generator = "seq_works")
    @Column(name = "workid", unique = true, nullable = false)
    public Integer getWorkid() {
        return this.workid;
    }

    public void setWorkid(Integer workid) {
        this.workid = workid;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "goodid")
    public Goods getGoods() {
        return this.goods;
    }

    public void setGoods(Goods goods) {
        this.goods = goods;
    }

    @Column(name = "workname", nullable = false, length = 50)
    public String getWorkname() {
        return this.workname;
    }

    public void setWorkname(String workname) {
        this.workname = workname;
    }

    @Column(name = "norma", nullable = false, precision = 17, scale = 17)
    public double getNorma() {
        return this.norma;
    }

    public void setNorma(double norma) {
        this.norma = norma;
    }

    @Column(name = "count", nullable = false)
    public int getCount() {
        return this.count;
    }

    public void setCount(int count) {
        this.count = count;
    }


}
